# Pipeline de validation sur la base du template "Starter pipeline"
# Elle est destinée à vérifier que la pipeline de déploiement fonctionnera avant de la rouler.
# Cela permet d'éviter un déploiement incomplet ou incorrect.

trigger:
  - master # le déclencheur est lié à la branche "master" du git

pool: "default" # notre pool d'agents locaux (nous en avons deux)

variables:
  - name: CloudInitContent # variable contenant les scripts de déploiement, vide au départ

steps:
  # script de récupération et de chiffrement du CloudInitContent
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $CloudContent = Get-Content -Path .\AzureRessourceGroup1\Cloud-init.txt -Raw
        Write-Host $CloudContent
        $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
        Write-Host $encodedContent
        Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

  # débug : vérification du CloudInitContent par affichage dans les logs
  - script: |
      echo $(CloudInitContent)

  # déploiement du Resource Group contenant le Linux Scale Set (VMSS)
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group" # déploiement à l'échelle d'un Resource Group
      azureResourceManagerConnection: "Azure subscription 1(e81592a2-5b66-4be5-8e47-eb76c109ccf2)" # l'abonnement Azure d'Elias
      subscriptionId: "e81592a2-5b66-4be5-8e47-eb76c109ccf2" # même chose
      action: "Create Or Update Resource Group" # "créer ou mettre à jour un Resource Group"
      resourceGroupName: "ScaleSetRG" # ce sera le Resource Group du Scale Set
      location: "East US" # y avait plus de machines au canada
      templateLocation: "Linked artifact"
      csmFile: "$(System.DefaultWorkingDirectory)/AzureRessourceGroup1/azuredeploy.json" # chemin du template
      csmParametersFile: "$(System.DefaultWorkingDirectory)/AzureRessourceGroup1/azuredeploy.parameters.json" # chemin des paramètres du template
      overrideParameters: "-customData $(CloudInitContent) -adminPassword $(AdminPass)"
      deploymentMode: "Validation Only" # validation seulement, pas de déploiement

  # déploiement du KeyVault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: "Azure subscription 1(e81592a2-5b66-4be5-8e47-eb76c109ccf2)" # l'abonnement Azure d'Elias
      KeyVaultName: "keyvaultprojet6" # nom du KeyVault
      SecretsFilter: "*" # prendre tous les secrets
      RunAsPreJob: false # nos jobs ne dépendent pas du KeyVault
