# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
- name: CloudInitContent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path .\AzureRessourceGroup1\Cloud-init.txt -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- script: |
    echo $(CloudInitContent)


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(e81592a2-5b66-4be5-8e47-eb76c109ccf2)'
    subscriptionId: 'e81592a2-5b66-4be5-8e47-eb76c109ccf2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KeyVaultRG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/AzureRessourceGroup1/azuredeploy.json'
    csmParametersFile: ''
    deploymentMode: 'Incremental'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(e81592a2-5b66-4be5-8e47-eb76c109ccf2)'
    KeyVaultName: 'keyvaultprojet1'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(e81592a2-5b66-4be5-8e47-eb76c109ccf2)'
    subscriptionId: 'e81592a2-5b66-4be5-8e47-eb76c109ccf2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRessourceGroup1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/AzureRessourceGroup1/azuredeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/AzureRessourceGroup1/azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'
